name: Upload Python Package to PyPI

on:
  release:
    types: [published]  # This will trigger the workflow only when a release is published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Set up the Python version (3.x uses the latest version of Python 3)

    - name: Extract tag name
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools

    - name: Build package
      run: |
        sed -i "s/version='.*'/version='${{ env.VERSION }}'/" setup.py
        python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.14
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
